name: JParty
dependencies:
  - requests==2.31.0
  - tornado==6.3.3
  - beautifulsoup4==4.11.1
  - pip
  - pip:
      - pyinstaller==6.6.0
      - pyqt6==6.4.0
      - qrcode==7.3.1
      - simpleaudio==1.0.4
