name: JParty
dependencies:
  - requests==2.32.4
  - tornado==6.5.1
  - beautifulsoup4==4.11.1
  - pip
  - pip:
      - pyinstaller==6.14.2
      - pyqt6==6.9.1
      - qrcode==7.3.1
      - simpleaudio==1.0.4
