name: Create Binaries

on:
   workflow_dispatch:

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - name: Install ALSA
        run: sudo apt-get install libasound2-dev
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.11'
          spec: 'JParty.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'JParty_linux'

  windows-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.11'
          spec: 'JParty.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'JParty_windows'

  macos-arm-build:
    runs-on: macos-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.11'
          spec: 'JParty.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'JParty_macos_arm'

  macos-x86-build:
    runs-on: macos-13
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.11'
          spec: 'JParty.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'JParty_macox_x86'
